name: Build

on:
  pull_request:
  push:
    branches:
      - main
      - staging
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm install

      - name: Type Check
        run: npm run type-check || echo "No type-check script"

      - name: Lint
        run: npm run lint || echo "No lint script"

      - name: Build
        run: npm run build || echo "No build script"
